modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="rebirth_inc"
version="1.0.0"
displayName="Rebirth_inc"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="isaac, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.rebirth_inc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.rebirth_inc]]
    modId="pehkui"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rebirth_inc]]
    modId="nexus_compiled_mods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rebirth_inc]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rebirth_inc]]
    modId="effekseer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rebirth_inc]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration